apiVersion: apps/v1
kind: Deployment
metadata:
  name: valhalla-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: valhalla
  template:
    metadata:
      labels:
        app: valhalla
    spec:
      containers:
      - name: valhalla-container
        image: your-ecr-url/valhalla:latest  # Replace with your ECR URL
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: valhalla-service
spec:
  selector:
    app: valhalla
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: LoadBalancer
